# -*- coding: utf-8 -*-
"""EDA DATA.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eph0vcb8yXgFsr6oMitRmxFtClvRPU64
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- TASK 1: Generate Synthetic Dataset (1000 rows) ---
np.random.seed(42)
n_rows = 1000

data = {
    'CustomerID': range(1001, 1001 + n_rows),
    'Age': np.random.randint(18, 70, size=n_rows),
    'PurchaseAmount': np.round(np.random.normal(250, 75, size=n_rows), 2),
    'ProductCategory': np.random.choice(['Electronics', 'Apparel', 'Groceries', 'Home', 'Beauty'], size=n_rows),
    'TransactionDate': pd.to_datetime('2025-01-01') + pd.to_timedelta(np.random.randint(0, 365, size=n_rows), unit='D')
}

df = pd.DataFrame(data)

# --- TASK 2: Initial Data Inspection ---
print("--- Data Inspection ---")
print(f"Shape: {df.shape}") # Rows and Columns
print(f"Data Types:\n{df.dtypes}\n")
print(f"Missing Values:\n{df.isnull().sum()}") # Check for missing values

# --- TASK 3: Key Descriptive Statistics ---
# Numerical: Mean, Median, Std Dev
num_stats = df[['Age', 'PurchaseAmount']].agg(['mean', 'median', 'std']).round(2)
# Categorical: Frequency counts for top 5
cat_stats = df['ProductCategory'].value_counts().head(5)

print("\n--- Numerical Statistics ---")
print(num_stats)
print("\n--- Top 5 Categories ---")
print(cat_stats)

# --- TASK 4: Three Distinct Visualizations ---
plt.figure(figsize=(15, 5))

# 1. Histogram (Numerical Feature)
plt.subplot(1, 3, 1)
sns.histplot(df['PurchaseAmount'], bins=25, kde=True, color='teal')
plt.title('Distribution of Purchase Amount')

# 2. Bar Chart (Categorical Distribution)
plt.subplot(1, 3, 2)
cat_stats.plot(kind='bar', color='salmon')
plt.title('Frequency of Product Categories')
plt.xticks(rotation=45)

# 3. Box Plot (Relationship between Categorical/Numerical)
plt.subplot(1, 3, 3)
sns.boxplot(x='ProductCategory', y='PurchaseAmount', data=df, palette='Set2')
plt.title('Purchase Amount by Category')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()
